version: '2'
services:
    nginx:
        links:
            - image_processor
    image_processor:
        domainname: ${IMAGE_PROCESSOR_DOMAIN_NAME}
        hostname: ${APP_ENV}-image-processor
        build:
            context: ${IMAGE_PROCESSOR_DOCKERFILE_DIR}/docker
        volumes:
            - "${IMAGE_PROCESSOR_DOCKERFILE_DIR}:${IMAGE_PROCESSOR_PROJECT_ROOT_PATH}"
            - "~/.aws/:/root/.aws"
        environment:
          - AWS_PROFILE=sandwhichi
        working_dir: ${IMAGE_PROCESSOR_PROJECT_ROOT_PATH}
        restart: always
        command: sh /var/entrypoint/${APP_ENV}.sh ${API_PROJECT_ROOT_PATH}
        stdin_open: true
        tty: true